// Profile form constants: colleges, degrees, branches, skills, roles, locations
export const INTEREST_OPTIONS = [
  "Jobs",
  "Internships",
  "Hackathons",
  "Scholarships",
  "Events",
  "Freelancing",
];

// Comprehensive list of Indian colleges/universities
export const COLLEGES = [
  // IITs
  { value: "iit-bombay", label: "IIT Bombay", type: "IIT" },
  { value: "iit-delhi", label: "IIT Delhi", type: "IIT" },
  { value: "iit-madras", label: "IIT Madras", type: "IIT" },
  { value: "iit-kanpur", label: "IIT Kanpur", type: "IIT" },
  { value: "iit-kharagpur", label: "IIT Kharagpur", type: "IIT" },
  { value: "iit-roorkee", label: "IIT Roorkee", type: "IIT" },
  { value: "iit-guwahati", label: "IIT Guwahati", type: "IIT" },
  { value: "iit-hyderabad", label: "IIT Hyderabad", type: "IIT" },
  { value: "iit-indore", label: "IIT Indore", type: "IIT" },
  { value: "iit-ropar", label: "IIT Ropar", type: "IIT" },
  { value: "iit-varanasi", label: "IIT (BHU) Varanasi", type: "IIT" },
  { value: "iit-goa", label: "IIT Goa", type: "IIT" },
  { value: "iit-tirupati", label: "IIT Tirupati", type: "IIT" },
  { value: "iit-dharwad", label: "IIT Dharwad", type: "IIT" },
  { value: "iit-jodhpur", label: "IIT Jodhpur", type: "IIT" },
  { value: "iit-mandi", label: "IIT Mandi", type: "IIT" },
  { value: "iit-bhilai", label: "IIT Bhilai", type: "IIT" },
  { value: "iit-dharwad", label: "IIT Dharwad", type: "IIT" },
  { value: "iit-palakkad", label: "IIT Palakkad", type: "IIT" },
  { value: "iit-tiruchirappalli", label: "IIT Tiruchirappalli", type: "IIT" },
  { value: "iit-(bhu)", label: "IIT (BHU) Varanasi", type: "IIT" },
  // NITs
  { value: "nits-trichy", label: "NIT Trichy", type: "NIT" },
  { value: "nits-surathkal", label: "NIT Surathkal", type: "NIT" },
  { value: "nits-warangal", label: "NIT Warangal", type: "NIT" },
  { value: "nits-calicut", label: "NIT Calicut", type: "NIT" },
  { value: "nits-pune", label: "NIT Pune", type: "NIT" },
  { value: "nits-raipur", label: "NIT Raipur", type: "NIT" },
  { value: "nits-rourkela", label: "NIT Rourkela", type: "NIT" },
  { value: "nits-jamshedpur", label: "NIT Jamshedpur", type: "NIT" },
  { value: "nits-kurukshetra", label: "NIT Kurukshetra", type: "NIT" },
  { value: "nits-hamirpur", label: "NIT Hamirpur", type: "NIT" },
  { value: "nits-srinagar", label: "NIT Srinagar", type: "NIT" },
  { value: "nits-delhi", label: "NIT Delhi", type: "NIT" },
  { value: "nits-goa", label: "NIT Goa", type: "NIT" },
  { value: "nits-agartala", label: "NIT Agartala", type: "NIT" },
  { value: "nits-bhopal", label: "NIT Bhopal", type: "NIT" },
  { value: "nits-jalandhar", label: "NIT Jalandhar", type: "NIT" },
  { value: "nits-Allahabad", label: "MNNIT Allahabad", type: "NIT" },
  { value: "nits-patna", label: "NIT Patna", type: "NIT" },
  // IIITs
  { value: "iiit-hyderabad", label: "IIIT Hyderabad", type: "IIIT" },
  { value: "iiit-bangalore", label: "IIIT Bangalore", type: "IIIT" },
  { value: "iiit-delhi", label: "IIIT Delhi", type: "IIIT" },
  { value: "iiit-pune", label: "IIIT Pune", type: "IIIT" },
  { value: "iiit-sricity", label: "IIIT Sricity", type: "IIIT" },
  { value: "iiit-nagpur", label: "IIIT Nagpur", type: "IIIT" },
  { value: "iiit-bhagalpur", label: "IIIT Bhagalpur", type: "IIIT" },
  { value: "iiit-kottayam", label: "IIIT Kottayam", type: "IIIT" },
  { value: "iiit-guwahati", label: "IIIT Guwahati", type: "IIIT" },
  { value: "iiit-lucknow", label: "IIIT Lucknow", type: "IIIT" },
  // BITS
  { value: "bits-pilani", label: "BITS Pilani", type: "Private" },
  { value: "bits-goa", label: "BITS Goa", type: "Private" },
  { value: "bits-hyderabad", label: "BITS Hyderabad", type: "Private" },
  { value: "bits-mesh", label: "BITS Mesra", type: "Private" },
  // VIT
  { value: "vit-vellore", label: "VIT Vellore", type: "Private" },
  { value: "vit-chennai", label: "VIT Chennai", type: "Private" },
  { value: "vit-ap", label: "VIT-AP (Amaravati)", type: "Private" },
  { value: "vit-bhopal", label: "VIT Bhopal", type: "Private" },
  // Other Top Private
  { value: "srm-chennai", label: "SRM Institute Chennai", type: "Private" },
  { value: "srm-ramapuram", label: "SRM Ramapuram", type: "Private" },
  { value: "amrita-coimbatore", label: "Amrita Vishwa Vidyapeetham, Coimbatore", type: "Private" },
  { value: "amrita-bengaluru", label: "Amrita Vishwa Vidyapeetham, Bengaluru", type: "Private" },
  { value: "manipal-bengaluru", label: "Manipal Institute, Bengaluru", type: "Private" },
  { value: "mit-manipal", label: "MIT Manipal", type: "Private" },
  { value: "vit-me", label: "Vellore Institute of Technology, Vellore", type: "Private" },
  { value: "psg-coimbatore", label: "PSG College of Technology", type: "Private" },
  { value: "kongu-erode", label: "Kongu Engineering College", type: "Private" },
  { value: "nitte-mangalore", label: "NITTE Meenakshi Institute of Technology", type: "Private" },
  { value: "rvce-bengaluru", label: "RV College of Engineering", type: "Private" },
  { value: "ms-ramaiah", label: "MS Ramaiah Institute of Technology", type: "Private" },
  { value: "pes-bengaluru", label: "PES University", type: "Private" },
  { value: "bms-bengaluru", label: "BMS College of Engineering", type: "Private" },
  { value: "dsce-bengaluru", label: "Dayananda Sagar College of Engineering", type: "Private" },
  { value: "nie-mysore", label: "NIE Mysore", type: "Private" },
  // Delhi NCR
  { value: "dtu-delhi", label: "DTU Delhi", type: "State" },
  { value: "nsut-delhi", label: "NSUT Delhi", type: "State" },
  { value: "igdtuw-delhi", label: "IGDTUW Delhi", type: "State" },
  { value: "iiit-delhi", label: "IIIT Delhi", type: "State" },
  { value: "bp-delhi", label: "BP India Delhi", type: "State" },
  { value: "jamia-delhi", label: "Jamia Millia Islamia", type: "Central" },
  { value: "jnu-delhi", label: "JNU Delhi", type: "Central" },
  { value: "du-delhi", label: "University of Delhi", type: "Central" },
  // Maharashtra
  { value: "coep-pune", label: "COEP Pune", type: "State" },
  { value: "vjti-mumbai", label: "VJTI Mumbai", type: "State" },
  { value: "spit-mumbai", label: "SPIT Mumbai", type: "Private" },
  { value: "wce-sangli", label: "Walchand College of Engineering", type: "State" },
  { value: "pict-pune", label: "PICT Pune", type: "Private" },
  { value: "vite-pune", label: "VIT Pune", type: "Private" },
  // Karnataka
  { value: "nie-mysuru", label: "NIE Mysuru", type: "Private" },
  { value: "uvce-bengaluru", label: "UVCE Bangalore", type: "State" },
  // Tamil Nadu
  { value: "cusat-kochi", label: "CUSAT Kochi", type: "State" },
  { value: "ceg-chennai", label: "CEG Anna University", type: "State" },
  { value: "psg-coimbatore", label: "PSG College of Technology", type: "Private" },
  // West Bengal
  { value: "jadavpur-kolkata", label: "Jadavpur University", type: "State" },
  { value: "kgp-iit", label: "IIT Kharagpur", type: "IIT" },
  { value: "cu-kolkata", label: "University of Calcutta", type: "State" },
  // Telangana
  { value: "osmania-hyderabad", label: "Osmania University", type: "State" },
  { value: "jntuh-hyderabad", label: "JNTUH Hyderabad", type: "State" },
  // Other States
  { value: "nitk-surathkal", label: "NITK Surathkal", type: "NIT" },
  { value: "lpu-phagwara", label: "LPU Phagwara", type: "Private" },
  { value: "cu-himachal", label: "Chandigarh University", type: "Private" },
  { value: "kiit-bhubaneswar", label: "KIIT Bhubaneswar", type: "Private" },
  { value: "bits-mesra", label: "BITS Mesra", type: "Private" },
  { value: "siksha-bhubaneswar", label: "Siksha 'O' Anusandhan", type: "Private" },
  { value: "cv-raman-bhubaneswar", label: "C.V. Raman College of Engineering", type: "Private" },
  // Other Government
  { value: "PEC-chandigarh", label: "PEC Chandigarh", type: "Government" },
  { value: "hbtu-kanpur", label: "HBTU Kanpur", type: "Government" },
  { value: "giani-zail-bhatia", label: "Giani Zail Singh Campus", type: "Government" },
  { value: "thapar-patiala", label: "Thapar Institute of Engineering and Technology", type: "Private" },
  { value: "bit-meshra", label: "BIT Mesra", type: "Private" },
  { value: "aiims-delhi", label: "AIIMS Delhi (Medical)", type: "Government" },
  // Generic Options
  { value: "other-iit", label: "Other IIT", type: "IIT" },
  { value: "other-nit", label: "Other NIT", type: "NIT" },
  { value: "other-iiit", label: "Other IIIT", type: "IIIT" },
  { value: "other-govt", label: "Other Government Institute", type: "Government" },
  { value: "other-private", label: "Other Private Institute", type: "Private" },
];

// Degrees
export const DEGREES = [
  { value: "btech", label: "B.Tech (Bachelor of Technology)", category: "Bachelor" },
  { value: "btech-cs", label: "B.Tech in Computer Science", category: "Bachelor" },
  { value: "btech-it", label: "B.Tech in Information Technology", category: "Bachelor" },
  { value: "btech-ec", label: "B.Tech in Electronics & Comm", category: "Bachelor" },
  { value: "btech-me", label: "B.Tech in Mechanical Engineering", category: "Bachelor" },
  { value: "btech-ce", label: "B.Tech in Civil Engineering", category: "Bachelor" },
  { value: "btech-ee", label: "B.Tech in Electrical Engineering", category: "Bachelor" },
  { value: "bsc-cs", label: "B.Sc in Computer Science", category: "Bachelor" },
  { value: "bsc-it", label: "B.Sc in Information Technology", category: "Bachelor" },
  { value: "bsc-physics", label: "B.Sc in Physics", category: "Bachelor" },
  { value: "bsc-maths", label: "B.Sc in Mathematics", category: "Bachelor" },
  { value: "bsc-chemistry", label: "B.Sc in Chemistry", category: "Bachelor" },
  { value: "bca", label: "BCA (Bachelor of Computer Applications)", category: "Bachelor" },
  { value: "bba", label: "BBA (Bachelor of Business Administration)", category: "Bachelor" },
  { value: "bcom", label: "B.Com (Bachelor of Commerce)", category: "Bachelor" },
  { value: "ba-economics", label: "BA in Economics", category: "Bachelor" },
  { value: "ba-english", label: "BA in English", category: "Bachelor" },
  { value: "mtech", label: "M.Tech (Master of Technology)", category: "Master" },
  { value: "mtech-cs", label: "M.Tech in Computer Science", category: "Master" },
  { value: "msc-cs", label: "M.Sc in Computer Science", category: "Master" },
  { value: "msc-it", label: "M.Sc in Information Technology", category: "Master" },
  { value: "msc-physics", label: "M.Sc in Physics", category: "Master" },
  { value: "msc-maths", label: "M.Sc in Mathematics", category: "Master" },
  { value: "mca", label: "MCA (Master of Computer Applications)", category: "Master" },
  { value: "mba", label: "MBA (Master of Business Administration)", category: "Master" },
  { value: "mba-fin", label: "MBA in Finance", category: "Master" },
  { value: "mba-mkt", label: "MBA in Marketing", category: "Master" },
  { value: "mba-hr", label: "MBA in HR", category: "Master" },
  { value: "mba-ops", label: "MBA in Operations", category: "Master" },
  { value: "mcom", label: "M.Com (Master of Commerce)", category: "Master" },
  { value: "ma-economics", label: "MA in Economics", category: "Master" },
  { value: "ma-english", label: "MA in English", category: "Master" },
  { value: "phd-cs", label: "PhD in Computer Science", category: "Doctorate" },
  { value: "phd", label: "PhD (Doctor of Philosophy)", category: "Doctorate" },
  { value: "diploma", label: "Diploma", category: "Diploma" },
  { value: "polytechnic", label: "Polytechnic Diploma", category: "Diploma" },
];

// Common branches/majors
export const BRANCHES = [
  { value: "computer-science", label: "Computer Science & Engineering" },
  { value: "information-technology", label: "Information Technology" },
  { value: "electronics-communication", label: "Electronics & Communication" },
  { value: "electrical", label: "Electrical Engineering" },
  { value: "mechanical", label: "Mechanical Engineering" },
  { value: "civil", label: "Civil Engineering" },
  { value: "chemical", label: "Chemical Engineering" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "aerospace", label: "Aerospace Engineering" },
  { value: "automobile", label: "Automobile Engineering" },
  { value: "instrumentation", label: "Instrumentation Engineering" },
  { value: "production", label: "Production Engineering" },
  { value: "metallurgy", label: "Metallurgy & Materials" },
  { value: "data-science", label: "Data Science" },
  { value: "ai-ml", label: "Artificial Intelligence & ML" },
  { value: "cybersecurity", label: "Cyber Security" },
  { value: "cloud", label: "Cloud Computing" },
  { value: "devops", label: "DevOps" },
  { value: "blockchain", label: "Blockchain Technology" },
  { value: "iot", label: "Internet of Things" },
  { value: "robotics", label: "Robotics & Automation" },
  { value: "pharmacology", label: "Pharmacology" },
  { value: "chemistry", label: "Chemistry" },
  { value: "physics", label: "Physics" },
  { value: "mathematics", label: "Mathematics" },
  { value: "statistics", label: "Statistics" },
  { value: "economics", label: "Economics" },
  { value: "commerce", label: "Commerce" },
  { value: "business-admin", label: "Business Administration" },
  { value: "management", label: "Management" },
  { value: "law", label: "Law" },
  { value: "design", label: "Design" },
  { value: "architecture", label: "Architecture" },
];

// Comprehensive skills list
export const SKILLS = [
  // Programming Languages
  { value: "python", label: "Python", category: "Programming" },
  { value: "javascript", label: "JavaScript", category: "Programming" },
  { value: "typescript", label: "TypeScript", category: "Programming" },
  { value: "java", label: "Java", category: "Programming" },
  { value: "c", label: "C", category: "Programming" },
  { value: "cpp", label: "C++", category: "Programming" },
  { value: "csharp", label: "C#", category: "Programming" },
  { value: "go", label: "Go", category: "Programming" },
  { value: "rust", label: "Rust", category: "Programming" },
  { value: "ruby", label: "Ruby", category: "Programming" },
  { value: "php", label: "PHP", category: "Programming" },
  { value: "swift", label: "Swift", category: "Programming" },
  { value: "kotlin", label: "Kotlin", category: "Programming" },
  { value: "scala", label: "Scala", category: "Programming" },
  { value: "r", label: "R", category: "Programming" },
  { value: "matlab", label: "MATLAB", category: "Programming" },
  { value: "perl", label: "Perl", category: "Programming" },
  { value: "shell", label: "Shell Scripting", category: "Programming" },
  { value: "powershell", label: "PowerShell", category: "Programming" },
  { value: "lua", label: "Lua", category: "Programming" },
  { value: "dart", label: "Dart", category: "Programming" },
  { value: "elixir", label: "Elixir", category: "Programming" },
  { value: "clojure", label: "Clojure", category: "Programming" },
  { value: "haskell", label: "Haskell", category: "Programming" },
  { value: "assembly", label: "Assembly", category: "Programming" },
  { value: "julia", label: "Julia", category: "Programming" },
  { value: "zig", label: "Zig", category: "Programming" },
  { value: "nim", label: "Nim", category: "Programming" },

  // AI / Agentic AI - NEW CATEGORY
  { value: "agentic-ai", label: "Agentic AI", category: "AI Agent" },
  { value: "llm", label: "Large Language Models (LLM)", category: "AI Agent" },
  { value: "gpt", label: "GPT / OpenAI API", category: "AI Agent" },
  { value: "claude", label: "Claude / Anthropic API", category: "AI Agent" },
  { value: "gemini", label: "Gemini / Google AI", category: "AI Agent" },
  { value: "langchain", label: "LangChain", category: "AI Agent" },
  { value: "langgraph", label: "LangGraph", category: "AI Agent" },
  { value: "llamaindex", label: "LlamaIndex", category: "AI Agent" },
  { value: "autogen", label: "AutoGen", category: "AI Agent" },
  { value: "crewai", label: "CrewAI", category: "AI Agent" },
  { value: "å·®åˆ†", label: "å·®åˆ† (Dify)", category: "AI Agent" },
  { value: "flowise", label: "Flowise", category: "AI Agent" },
  { value: "haystack", label: "Haystack", category: "AI Agent" },
  { value: "chainlit", label: "Chainlit", category: "AI Agent" },
  { value: "instructor", label: "Instructor", category: "AI Agent" },
  { value: "litellm", label: "LiteLLM", category: "AI Agent" },
  { value: "vllm", label: "vLLM", category: "AI Agent" },
  { value: "ollama", label: "Ollama", category: "AI Agent" },
  { value: "transformers", label: "Hugging Face Transformers", category: "AI Agent" },
  { value: "tokenizers", label: "Hugging Face Tokenizers", category: "AI Agent" },
  { value: "datasets", label: "Hugging Face Datasets", category: "AI Agent" },
  { value: "peft", label: "PEFT (LoRA, QLoRA)", category: "AI Agent" },
  { value: "trl", label: "TRL (Transformer Reinforcement Learning)", category: "AI Agent" },
  { value: "axolotl", label: "Axolotl", category: "AI Agent" },
  { value: "prompt-engineering", label: "Prompt Engineering", category: "AI Agent" },
  { value: "rag", label: "RAG (Retrieval Augmented Generation)", category: "AI Agent" },
  { value: "vector-db", label: "Vector Databases (Pinecone, Weaviate, etc.)", category: "AI Agent" },
  { value: "milvus", label: "Milvus", category: "AI Agent" },
  { value: "chroma", label: "ChromaDB", category: "AI Agent" },
  { value: "qdrant", label: "Qdrant", category: "AI Agent" },
  { value: "faiss", label: "FAISS", category: "AI Agent" },
  { value: "embeddings", label: "Embeddings (OpenAI, Cohere, etc.)", category: "AI Agent" },
  { value: "ai-safety", label: "AI Safety & Alignment", category: "AI Agent" },
  { value: "hallucination-detection", label: "Hallucination Detection", category: "AI Agent" },
  { value: "function-calling", label: "Function Calling / Tool Use", category: "AI Agent" },
  { value: "mcp", label: "Model Context Protocol (MCP)", category: "AI Agent" },
  { value: "computer-use", label: "Computer Use / AI Agents", category: "AI Agent" },
  { value: "web-search", label: "Web Search Integration (SerpAPI, DuckDuckGo)", category: "AI Agent" },

  // Frontend
  { value: "react", label: "React", category: "Frontend" },
  { value: "react-native", label: "React Native", category: "Frontend" },
  { value: "nextjs", label: "Next.js", category: "Frontend" },
  { value: "vue", label: "Vue.js", category: "Frontend" },
  { value: "nuxt", label: "Nuxt.js", category: "Frontend" },
  { value: "angular", label: "Angular", category: "Frontend" },
  { value: "svelte", label: "Svelte", category: "Frontend" },
  { value: "sveltekit", label: "SvelteKit", category: "Frontend" },
  { value: "html", label: "HTML", category: "Frontend" },
  { value: "css", label: "CSS", category: "Frontend" },
  { value: "sass", label: "SASS/SCSS", category: "Frontend" },
  { value: "tailwind", label: "Tailwind CSS", category: "Frontend" },
  { value: "bootstrap", label: "Bootstrap", category: "Frontend" },
  { value: "material-ui", label: "Material UI", category: "Frontend" },
  { value: "framer-motion", label: "Framer Motion", category: "Frontend" },
  { value: "greensock", label: "GSAP/GreenSock", category: "Frontend" },
  { value: "threejs", label: "Three.js", category: "Frontend" },
  { value: "webgl", label: "WebGL", category: "Frontend" },
  { value: "redux", label: "Redux", category: "Frontend" },
  { value: "zustand", label: "Zustand", category: "Frontend" },
  { value: "mobx", label: "MobX", category: "Frontend" },
  { value: "graphql", label: "GraphQL", category: "Frontend" },
  { value: "apollo", label: "Apollo Client", category: "Frontend" },
  { value: "axios", label: "Axios", category: "Frontend" },
  { value: "tanstack-query", label: "TanStack Query", category: "Frontend" },
  { value: "astro", label: "Astro", category: "Frontend" },
  { value: "remix", label: "Remix", category: "Frontend" },
  { value: "qwik", label: "Qwik", category: "Frontend" },

  // Backend
  { value: "nodejs", label: "Node.js", category: "Backend" },
  { value: "express", label: "Express.js", category: "Backend" },
  { value: "fastify", label: "Fastify", category: "Backend" },
  { value: "nestjs", label: "NestJS", category: "Backend" },
  { value: "django", label: "Django", category: "Backend" },
  { value: "flask", label: "Flask", category: "Backend" },
  { value: "fastapi", label: "FastAPI", category: "Backend" },
  { value: "spring", label: "Spring Boot", category: "Backend" },
  { value: "spring-security", label: "Spring Security", category: "Backend" },
  { value: "rails", label: "Ruby on Rails", category: "Backend" },
  { value: "laravel", label: "Laravel", category: "Backend" },
  { value: "aspnet", label: "ASP.NET", category: "Backend" },
  { value: "fiber", label: "Fiber (Go)", category: "Backend" },
  { value: "gin", label: "Gin (Go)", category: "Backend" },
  { value: "chi", label: "Chi (Go)", category: "Backend" },
  { value: "echo", label: "Echo (Go)", category: "Backend" },
  { value: "play", label: "Play Framework", category: "Backend" },
  { value: "grpc", label: "gRPC", category: "Backend" },
  { value: "rest-api", label: "REST API Design", category: "Backend" },
  { value: "websockets", label: "WebSockets", category: "Backend" },
  { value: "socketio", label: "Socket.IO", category: "Backend" },
  { value: "hapi", label: "Hapi.js", category: "Backend" },
  { value: "koa", label: "Koa.js", category: "Backend" },
  { value: "adonisjs", label: "AdonisJS", category: "Backend" },

  // Databases
  { value: "mysql", label: "MySQL", category: "Database" },
  { value: "postgresql", label: "PostgreSQL", category: "Database" },
  { value: "mongodb", label: "MongoDB", category: "Database" },
  { value: "redis", label: "Redis", category: "Database" },
  { value: "elasticsearch", label: "Elasticsearch", category: "Database" },
  { value: "cassandra", label: "Cassandra", category: "Database" },
  { value: "dynamodb", label: "DynamoDB", category: "Database" },
  { value: "firebase", label: "Firebase", category: "Database" },
  { value: "supabase", label: "Supabase", category: "Database" },
  { value: "sqlite", label: "SQLite", category: "Database" },
  { value: "mariadb", label: "MariaDB", category: "Database" },
  { value: "mssql", label: "MS SQL Server", category: "Database" },
  { value: "oracle", label: "Oracle", category: "Database" },
  { value: "neo4j", label: "Neo4j", category: "Database" },
  { value: "couchdb", label: "CouchDB", category: "Database" },
  { value: "prisma", label: "Prisma", category: "Database" },
  { value: "drizzle", label: "Drizzle ORM", category: "Database" },
  { value: "sqlalchemy", label: "SQLAlchemy", category: "Database" },
  { value: "typeorm", label: "TypeORM", category: "Database" },

  // DevOps & Cloud
  { value: "aws", label: "AWS", category: "Cloud" },
  { value: "azure", label: "Azure", category: "Cloud" },
  { value: "gcp", label: "Google Cloud Platform", category: "Cloud" },
  { value: "digitalocean", label: "DigitalOcean", category: "Cloud" },
  { value: "heroku", label: "Heroku", category: "Cloud" },
  { value: "vercel", label: "Vercel", category: "Cloud" },
  { value: "netlify", label: "Netlify", category: "Cloud" },
  { value: "cloudflare", label: "Cloudflare", category: "Cloud" },
  { value: "aws-lambda", label: "AWS Lambda", category: "Cloud" },
  { value: "aws-s3", label: "AWS S3", category: "Cloud" },
  { value: "aws-ec2", label: "AWS EC2", category: "Cloud" },
  { value: "aws-ecs", label: "AWS ECS / EKS", category: "Cloud" },
  { value: "gcp-cloud-functions", label: "GCP Cloud Functions", category: "Cloud" },
  { value: "docker", label: "Docker", category: "DevOps" },
  { value: "kubernetes", label: "Kubernetes", category: "DevOps" },
  { value: "jenkins", label: "Jenkins", category: "DevOps" },
  { value: "gitlab-ci", label: "GitLab CI/CD", category: "DevOps" },
  { value: "github-actions", label: "GitHub Actions", category: "DevOps" },
  { value: "circleci", label: "CircleCI", category: "DevOps" },
  { value: "travis-ci", label: "Travis CI", category: "DevOps" },
  { value: "terraform", label: "Terraform", category: "DevOps" },
  { value: "ansible", label: "Ansible", category: "DevOps" },
  { value: "puppet", label: "Puppet", category: "DevOps" },
  { value: "chef", label: "Chef", category: "DevOps" },
  { value: "prometheus", label: "Prometheus", category: "DevOps" },
  { value: "grafana", label: "Grafana", category: "DevOps" },
  { value: "elk-stack", label: "ELK Stack", category: "DevOps" },
  { value: "splunk", label: "Splunk", category: "DevOps" },
  { value: "nagios", label: "Nagios", category: "DevOps" },
  { value: "datadog", label: "Datadog", category: "DevOps" },
  { value: "newrelic", label: "New Relic", category: "DevOps" },
  { value: "argocd", label: "ArgoCD", category: "DevOps" },
  { value: "helm", label: "Helm", category: "DevOps" },
  { value: "istio", label: "Istio", category: "DevOps" },
  { value: "linkerd", label: "Linkerd", category: "DevOps" },

  // Data Science & ML
  { value: "machine-learning", label: "Machine Learning", category: "AI/ML" },
  { value: "deep-learning", label: "Deep Learning", category: "AI/ML" },
  { value: "tensorflow", label: "TensorFlow", category: "AI/ML" },
  { value: "pytorch", label: "PyTorch", category: "AI/ML" },
  { value: "keras", label: "Keras", category: "AI/ML" },
  { value: "scikit-learn", label: "Scikit-learn", category: "AI/ML" },
  { value: "pandas", label: "Pandas", category: "Data Science" },
  { value: "numpy", label: "NumPy", category: "Data Science" },
  { value: "scipy", label: "SciPy", category: "Data Science" },
  { value: "jupyter", label: "Jupyter", category: "Data Science" },
  { value: "tableau", label: "Tableau", category: "Data Science" },
  { value: "powerbi", label: "Power BI", category: "Data Science" },
  { value: "nlp", label: "Natural Language Processing", category: "AI/ML" },
  { value: "computer-vision", label: "Computer Vision", category: "AI/ML" },
  { value: "opencv", label: "OpenCV", category: "AI/ML" },
  { value: "hugging-face", label: "Hugging Face", category: "AI/ML" },
  { value: "langchain", label: "LangChain", category: "AI/ML" },
  { value: "llm", label: "LLMs / GPT", category: "AI/ML" },
  { value: "reinforcement", label: "Reinforcement Learning", category: "AI/ML" },
  { value: "statistics", label: "Statistics", category: "Data Science" },
  { value: "data-analysis", label: "Data Analysis", category: "Data Science" },
  { value: "data-visualization", label: "Data Visualization", category: "Data Science" },
  { value: "big-data", label: "Big Data", category: "Data Science" },
  { value: "spark", label: "Apache Spark", category: "Data Science" },
  { value: "hadoop", label: "Hadoop", category: "Data Science" },
  { value: "kafka", label: "Apache Kafka", category: "Data Science" },
  { value: "airflow", label: "Airflow", category: "Data Science" },
  { value: "pandas-profiling", label: "Pandas Profiling", category: "Data Science" },
  { value: "xgboost", label: "XGBoost", category: "AI/ML" },
  { value: "lightgbm", label: "LightGBM", category: "AI/ML" },
  { value: "catboost", label: "CatBoost", category: "AI/ML" },

  // Mobile
  { value: "android", label: "Android Development", category: "Mobile" },
  { value: "ios", label: "iOS Development", category: "Mobile" },
  { value: "flutter", label: "Flutter", category: "Mobile" },
  { value: "react-native", label: "React Native", category: "Mobile" },
  { value: "swiftui", label: "SwiftUI", category: "Mobile" },
  { value: "jetpack-compose", label: "Jetpack Compose", category: "Mobile" },
  { value: "xamarin", label: "Xamarin", category: "Mobile" },
  { value: "ionic", label: "Ionic", category: "Mobile" },
  { value: "expo", label: "Expo", category: "Mobile" },
  { value: "kivy", label: "Kivy", category: "Mobile" },

  // Design
  { value: "figma", label: "Figma", category: "Design" },
  { value: "sketch", label: "Sketch", category: "Design" },
  { value: "adobe-xd", label: "Adobe XD", category: "Design" },
  { value: "photoshop", label: "Adobe Photoshop", category: "Design" },
  { value: "illustrator", label: "Adobe Illustrator", category: "Design" },
  { value: "after-effects", label: "After Effects", category: "Design" },
  { value: "blender", label: "Blender", category: "Design" },
  { value: "ui-design", label: "UI Design", category: "Design" },
  { value: "ux-design", label: "UX Design", category: "Design" },
  { value: "motion-design", label: "Motion Design", category: "Design" },
  { value: "web-design", label: "Web Design", category: "Design" },
  { value: "figma-components", label: "Figma Components", category: "Design" },
  { value: "design-systems", label: "Design Systems", category: "Design" },

  // Security
  { value: "security", label: "Cybersecurity", category: "Security" },
  { value: "penetration-testing", label: "Penetration Testing", category: "Security" },
  { value: "ethical-hacking", label: "Ethical Hacking", category: "Security" },
  { value: "owasp", label: "OWASP", category: "Security" },
  { value: "iso-27001", label: "ISO 27001", category: "Security" },
  { value: "soc2", label: "SOC 2", category: "Security" },
  { value: "gdpr", label: "GDPR Compliance", category: "Security" },
  { value: "encryption", label: "Encryption", category: "Security" },
  { value: "jwt", label: "JWT", category: "Security" },
  { value: "oauth", label: "OAuth 2.0", category: "Security" },
  { value: "saml", label: "SAML", category: "Security" },
  { value: "keycloak", label: "Keycloak", category: "Security" },

  // Blockchain
  { value: "solidity", label: "Solidity", category: "Blockchain" },
  { value: "web3", label: "Web3", category: "Blockchain" },
  { value: "ethereum", label: "Ethereum", category: "Blockchain" },
  { value: "hyperledger", label: "Hyperledger", category: "Blockchain" },
  { value: "smart-contracts", label: "Smart Contracts", category: "Blockchain" },
  { value: "nft", label: "NFT Development", category: "Blockchain" },
  { value: "bitcoin", label: "Bitcoin", category: "Blockchain" },
  { value: "polygon", label: "Polygon", category: "Blockchain" },

  // Soft Skills & Other
  { value: "git", label: "Git", category: "Tools" },
  { value: "github", label: "GitHub", category: "Tools" },
  { value: "gitlab", label: "GitLab", category: "Tools" },
  { value: "jira", label: "Jira", category: "Tools" },
  { value: "confluence", label: "Confluence", category: "Tools" },
  { value: "slack", label: "Slack", category: "Tools" },
  { value: "trello", label: "Trello", category: "Tools" },
  { value: "notion", label: "Notion", category: "Tools" },
  { value: "asana", label: "Asana", category: "Tools" },
  { value: "linear", label: "Linear", category: "Tools" },
  { value: "clickup", label: "ClickUp", category: "Tools" },
  { value: "agile", label: "Agile Methodology", category: "Methodology" },
  { value: "scrum", label: "Scrum", category: "Methodology" },
  { value: "kanban", label: "Kanban", category: "Methodology" },
  { value: "linux", label: "Linux", category: "Operating Systems" },
  { value: "windows-server", label: "Windows Server", category: "Operating Systems" },
  { value: "unix", label: "Unix", category: "Operating Systems" },
  { value: "macos", label: "macOS", category: "Operating Systems" },
  { value: "networking", label: "Networking", category: "Infrastructure" },
  { value: "dns", label: "DNS", category: "Infrastructure" },
  { value: "cdn", label: "CDN", category: "Infrastructure" },
  { value: "ssl", label: "SSL/TLS", category: "Infrastructure" },
  { value: "api-design", label: "API Design", category: "Backend" },
  { value: "microservices", label: "Microservices", category: "Architecture" },
  { value: "serverless", label: "Serverless", category: "Architecture" },
  { value: "saas", label: "SaaS Architecture", category: "Architecture" },
  { value: "cqrs", label: "CQRS", category: "Architecture" },
  { value: "event-sourcing", label: "Event Sourcing", category: "Architecture" },
  { value: "ddd", label: "Domain Driven Design", category: "Architecture" },
  { value: "clean-architecture", label: "Clean Architecture", category: "Architecture" },
  { value: "hexagonal-architecture", label: "Hexagonal Architecture", category: "Architecture" },
];

// Skills by category for the dropdown
export const SKILLS_BY_CATEGORY = SKILLS.reduce((acc, skill) => {
  if (!acc[skill.category]) {
    acc[skill.category] = [];
  }
  acc[skill.category].push(skill);
  return acc;
}, {} as Record<string, typeof SKILLS>);

// Common job roles
export const JOB_ROLES = [
  // Software Development
  { value: "software-engineer", label: "Software Engineer" },
  { value: "frontend-developer", label: "Frontend Developer" },
  { value: "backend-developer", label: "Backend Developer" },
  { value: "full-stack-developer", label: "Full Stack Developer" },
  { value: "mobile-developer", label: "Mobile Developer" },
  { value: "devops-engineer", label: "DevOps Engineer" },
  { value: "platform-engineer", label: "Platform Engineer" },
  { value: "site-reliability", label: "SRE Engineer" },
  { value: "cloud-engineer", label: "Cloud Engineer" },
  { value: "infrastructure-engineer", label: "Infrastructure Engineer" },
  // AI & Data
  { value: "ai-engineer", label: "AI Engineer" },
  { value: "ml-engineer", label: "Machine Learning Engineer" },
  { value: "deep-learning-engineer", label: "Deep Learning Engineer" },
  { value: "nlp-engineer", label: "NLP Engineer" },
  { value: "computer-vision-engineer", label: "Computer Vision Engineer" },
  { value: "data-scientist", label: "Data Scientist" },
  { value: "data-analyst", label: "Data Analyst" },
  { value: "data-engineer", label: "Data Engineer" },
  { value: "analytics-engineer", label: "Analytics Engineer" },
  { value: "llm-engineer", label: "LLM Engineer" },
  { value: "prompt-engineer", label: "Prompt Engineer" },
  { value: "rag-engineer", label: "RAG Engineer" },
  { value: "ai-agent-developer", label: "AI Agent Developer" },
  // Product & Design
  { value: "product-manager", label: "Product Manager" },
  { value: "associate-product-manager", label: "Associate Product Manager" },
  { value: "product-designer", label: "Product Designer" },
  { value: "ux-designer", label: "UX Designer" },
  { value: "ui-designer", label: "UI Designer" },
  { value: "ux-researcher", label: "UX Researcher" },
  // QA & Security
  { value: "qa-engineer", label: "QA Engineer" },
  { value: "automation-qa", label: "Automation QA Engineer" },
  { value: "security-engineer", label: "Security Engineer" },
  { value: "penetration-tester", label: "Penetration Tester" },
  // Specialized Roles
  { value: "blockchain-developer", label: "Blockchain Developer" },
  { value: "game-developer", label: "Game Developer" },
  { value: "embedded-systems", label: "Embedded Systems Engineer" },
  { value: "electronics-engineer", label: "Electronics Engineer" },
  { value: "systems-engineer", label: "Systems Engineer" },
  { value: "network-engineer", label: "Network Engineer" },
  { value: "database-admin", label: "Database Administrator" },
  { value: "technical-program-manager", label: "Technical Program Manager" },
  // Leadership
  { value: "tech-lead", label: "Technical Lead" },
  { value: "engineering-manager", label: "Engineering Manager" },
  { value: "director-of-engineering", label: "Director of Engineering" },
  { value: "vp-engineering", label: "VP of Engineering" },
  { value: "solutions-architect", label: "Solutions Architect" },
  { value: "technical-architect", label: "Technical Architect" },
  { value: "enterprise-architect", label: "Enterprise Architect" },
  // Other
  { value: "business-analyst", label: "Business Analyst" },
  { value: "technical-writer", label: "Technical Writer" },
  { value: "developer-advocate", label: "Developer Advocate" },
  { value: "mechanical-engineer", label: "Mechanical Engineer" },
  { value: "civil-engineer", label: "Civil Engineer" },
  { value: "intern", label: "Intern" },
  { value: "trainee", label: "Trainee" },
  { value: "fresher", label: "Fresher / Entry Level" },
];

// Common locations
export const LOCATIONS = [
  // Major Tech Hubs
  { value: "bangalore", label: "Bangalore / Bengaluru" },
  { value: "hyderabad", label: "Hyderabad" },
  { value: "pune", label: "Pune" },
  { value: "chennai", label: "Chennai" },
  { value: "mumbai", label: "Mumbai" },
  { value: "delhi-ncr", label: "Delhi NCR" },
  { value: "gurugram", label: "Gurugram" },
  { value: "noida", label: "Noida" },
  // Other Cities
  { value: "kolkata", label: "Kolkata" },
  { value: "ahmedabad", label: "Ahmedabad" },
  { value: "jaipur", label: "Jaipur" },
  { value: "chandigarh", label: "Chandigarh" },
  { value: "lucknow", label: "Lucknow" },
  { value: "kochi", label: "Kochi" },
  { value: "coimbatore", label: "Coimbatore" },
  { value: "indore", label: "Indore" },
  { value: "bhopal", label: "Bhopal" },
  { value: "patna", label: "Patna" },
  { value: "nagpur", label: "Nagpur" },
  { value: "mangalore", label: "Mangalore" },
  { value: "mysore", label: "Mysore" },
  { value: "trivandrum", label: "Trivandrum" },
  { value: "visakhapatnam", label: "Visakhapatnam" },
  { value: "vijayawada", label: "Vijayawada" },
  { value: "goa", label: "Goa" },
  { value: "surat", label: "Surat" },
  { value: "vadodara", label: "Vadodara" },
  { value: "ranchi", label: "Ranchi" },
  { value: "dehradun", label: "Dehradun" },
  // Work Modes
  { value: "remote", label: "Remote / Work From Home" },
  { value: "hybrid", label: "Hybrid" },
  { value: "wfo", label: "Work From Office" },
];

// Graduation years
export const GRADUATION_YEARS = Array.from({ length: 10 }, (_, i) => ({
  value: (new Date().getFullYear() + 5 - i).toString(),
  label: (new Date().getFullYear() + 5 - i).toString(),
}));




